# # example
# # about download_dir:
# # - default: $MODEL_DIR/type/category
# # - priority: model.items.dir > model.dir > default
# [models.type]
# dir = "" ## optional, -> $MODEL_DIR/{model.dir}
# [[models.type.items]]
# category = "" ## optional, sd15, sdxl, etc. will use as a directory name. default: None
# tags = [] ## optional, tags for filtering
# dir = ""  ## optional, -> $MODEL_DIR/{model.items.dir}
# url = "https://example.com/model.ckpt"
# filename = "model.ckpt" ## optional, default: original filename
# post_script = "init-model.sh" ## TODO

# special path definition, will not respect items.category for these type
[models.ipadapter]
dir = "ipadapter"

# sd15
## sd15 ckpts & vae
### origin sd15
[[models.checkpoints.items]]
category = "sd15"
url = "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt"
[[models.vae.items]]
category = "sd15"
url = "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors"

### anything v5
[[models.checkpoints.items]]
category = "sd15"
tags = ["set-lite"]
url = "https://civitai.com/api/download/models/30163?type=Model&format=SafeTensor&size=full&fp=fp16"
filename = "AnythingV5_v5PrtRE.safetensors"

### dreamshaper 8
[[models.checkpoints.items]]
category = "sd15"
tags = ["set-lite"]
url = "https://civitai.com/api/download/models/128713?type=Model&format=SafeTensor&size=pruned&fp=fp16"

### dreamshaper 8 lcm
[[models.checkpoints.items]]
category = "sd15"
url = "https://civitai.com/api/download/models/252914?type=Model&format=SafeTensor&size=pruned&fp=fp16"

### orangemix vae
[[models.vae.items]]
category = "sd15"
url = "https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/VAEs/orangemix.vae.pt"

### wd14 vae
[[models.vae.items]]
category = "sd15"
url = "https://huggingface.co/hakurei/waifu-diffusion-v1-4/resolve/main/vae/kl-f8-anime2.ckpt"

## sd15 loras
### lcm sd15 lora
[[models.loras.items]]
category = "sd15"
url = "https://huggingface.co/latent-consistency/lcm-lora-sdv1-5/resolve/main/pytorch_lora_weights.safetensors"
filename = "lcm-lora-sdv1-5.safetensors"

# ### hyper-sd sd15 lora
# [[models.loras.items]]
# category = "sd15"
# url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SD15-1step-lora.safetensors"
# [[models.loras.items]]
# category = "sd15"
# url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SD15-2steps-lora.safetensors"
# [[models.loras.items]]
# category = "sd15"
# url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SD15-4steps-lora.safetensors"
# [[models.loras.items]]
# category = "sd15"
# url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SD15-8steps-lora.safetensors"

## sd15 controlnet
#TODO


## sd15 ipadapter
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15.safetensors"
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_light_v11.bin"
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sd15.safetensors"
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus-face_sd15.safetensors"
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-full-face_sd15.safetensors"
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_vit-G.safetensors"
### ip-composition-adapter
[[models.ipadapter.items]]
category = "sd15"
url = "https://huggingface.co/ostris/ip-composition-adapter/resolve/main/ip_plus_composition_sd15.safetensors"

# sdxl
## sdxl ckpts & vae
### origin sdxl 1.0
[[models.checkpoints.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors"
[[models.checkpoints.items]]
category = "sdxl"
url = "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors"
[[models.vae.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors"

### dreamshaper xl
#### v2.1 turbo dpm++ sde
[[models.checkpoints.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://civitai.com/api/download/models/351306?type=Model&format=SafeTensor&size=full&fp=fp16"

### kohaku-xl
[[models.checkpoints.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://huggingface.co/KBlueLeaf/Kohaku-XL-Epsilon/resolve/main/kohaku-xl-epsilon-rev1.safetensors"
[[models.vae.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://huggingface.co/KBlueLeaf/Kohaku-XL-Epsilon/blob/main/vae/diffusion_pytorch_model.bin"
filename = "vae_kohaku-xl-epsilon.bin"

### animaginexl
[[models.checkpoints.items]]
category = "sdxl"
url ="https://huggingface.co/cagliostrolab/animagine-xl-3.1/resolve/main/animagine-xl-3.1.safetensors"
[[models.vae.items]]
category = "sdxl"
url = "https://huggingface.co/cagliostrolab/animagine-xl-3.1/resolve/main/vae/diffusion_pytorch_model.safetensors"
filename = "vae_animagine-xl-3.1.safetensors"

### opendalle
[[models.checkpoints.items]]
category = "sdxl"
url = "https://huggingface.co/dataautogpt3/OpenDalleV1.1/resolve/main/OpenDalleV1.1.safetensors"

### neta_art_xl v1.0
[[models.checkpoints.items]]
category = "sdxl"
url = "https://civitai.com/api/download/models/457853?type=Model&format=SafeTensor&size=full&fp=fp16"


## sdxl loras
### anime fix hands lora by @bdsqlsz
[[models.loras.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://huggingface.co/bdsqlsz/stable-diffusion-xl-anime-5.2/resolve/main/Fixhands_anime_bdsqlsz_V1.safetensors"

### lcm lora (original)
[[models.loras.items]]
category = "sdxl"
url = "https://huggingface.co/latent-consistency/lcm-lora-sdxl/resolve/main/pytorch_lora_weights.safetensors"
filename = "lcm-lora-sdxl.safetensors"

### lcm & turbomix loras
#### (fix) sampler: euler a; scheduler: normal
[[models.loras.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://civitai.com/api/download/models/246747?type=Model&format=SafeTensor"
#### sampler: dpmpp_sde; scheduler: karras
[[models.loras.items]]
category = "sdxl"
tags = ["set-lite"]
url = "https://civitai.com/api/download/models/247778?type=Model&format=SafeTensor"
#### sampler: lcm; scheduler: sgm_uniform
[[models.loras.items]]
url = "https://civitai.com/api/download/models/268475?type=Model&format=SafeTensor"

### lightning loras
# #### 2step
# [[models.loras.items]]
# category = "sdxl"
# url = "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_2step_lora.safetensors"
# #### 4step
# [[models.loras.items]]
# category = "sdxl"
# url = "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_4step_lora.safetensors"
# #### 8step
# [[models.loras.items]]
# category = "sdxl"
# url = "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_8step_lora.safetensors"

# hyper-sd sdxl lora
[[models.loras.items]]
category = "sdxl"
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SDXL-1step-lora.safetensors"
[[models.loras.items]]
category = "sdxl"
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SDXL-2steps-lora.safetensors"
[[models.loras.items]]
category = "sdxl"
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SDXL-4steps-lora.safetensors"
[[models.loras.items]]
category = "sdxl"
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SDXL-8steps-lora.safetensors"


## sdxl controlnet
#TODO


## sdxl ipadapter
[[models.ipadapter.items]]
category = "sdxl"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors"
[[models.ipadapter.items]]
category = "sdxl"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors"
[[models.ipadapter.items]]
category = "sdxl"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors"
[[models.ipadapter.items]]
category = "sdxl"
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors"
### ip-composition-adapter
[[models.ipadapter.items]]
category = "sdxl"
url = "https://huggingface.co/ostris/ip-composition-adapter/resolve/main/ip_plus_composition_sdxl.safetensors"


## sdxl revision
[[models.clip_vision.items]]
url = "https://huggingface.co/stabilityai/control-lora/resolve/main/revision/clip_vision_g.safetensors"



# sd cascade
## original sd cascade
### stage a (vae)
[[models.vae.items]]
category = "sd-cascade"
url = "https://huggingface.co/stabilityai/stable-cascade/resolve/main/stage_a.safetensors"
### stage b
[[models.checkpoints.items]]
category = "sd-cascade"
url = "https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_b.safetensors"
### stage c
[[models.checkpoints.items]]
category = "sd-cascade"
url = "https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_c.safetensors"
### effnet_encode (vae for stage c latent)
[[models.vae.items]]
category = "sd-cascade"
url = "https://huggingface.co/stabilityai/stable-cascade/resolve/main/effnet_encoder.safetensors"
### text_encoder (CLIP)
[[models.clip.items]]
category = "sd-cascade"
url = "https://huggingface.co/stabilityai/stable-cascade/resolve/main/text_encoder/model.safetensors"