# # example
# [[custom_nodes]]
# url = ""
# post_script = "init-custom_node.sh" ## TODO

# # example
# # about download_dir:
# # - default: $MODEL_DIR/type/category
# # - priority: model.items.dir > model.dir > default
# [models.type]
# dir = "" ## optional, -> $MODEL_DIR/{model.dir}
# [[models.type.items]]
# category = "" ## optional, sd15, sdxl, etc. will use as a directory name. default: None
# dir = ""  ## optional, -> $MODEL_DIR/{model.items.dir}
# url = "https://example.com/model.ckpt"
# filename = "model.ckpt" ## optional, default: original filename
# post_script = "init-model.sh" ## TODO



[[custom_nodes]]
url = "https://github.com/ltdrdata/ComfyUI-Manager"

[[custom_nodes]]
url = "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes"

[[custom_nodes]]
url = "https://github.com/Fannovel16/comfyui_controlnet_aux"

[[custom_nodes]]
url = "https://github.com/cubiq/ComfyUI_InstantID"
# TODO: 
# - add pose_script to install insightface
# - download antelopev2 model into $MODEL_DIR/insightface/models/antelopev2
# - download instandid model into $MODEL_DIR/instantid (ip-adapter.bin & controlnet)
# ref: https://github.com/cubiq/ComfyUI_InstantID#installation

[[custom_nodes]]
url = "https://github.com/cubiq/ComfyUI_IPAdapter_plus"
[[models.clip_vision.items]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors"
filename = "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors"
[[models.clip_vision.items]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors"
filename = "CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors"

[[custom_nodes]]
url = "https://github.com/talesofai/comfyui-browser"

[[custom_nodes]]
url = "https://github.com/crystian/ComfyUI-Crystools"

[[custom_nodes]]
url = "https://github.com/pythongosssss/ComfyUI-Custom-Scripts"

[[custom_nodes]]
url = "https://github.com/BennyKok/comfyui-deploy"

[[custom_nodes]]
url = "https://github.com/ltdrdata/ComfyUI-Impact-Pack"

[[custom_nodes]]
url = "https://github.com/Acly/comfyui-inpaint-nodes"

[[custom_nodes]]
url = "https://github.com/huchenlei/ComfyUI-layerdiffuse"

[[custom_nodes]]
url = "https://github.com/pythongosssss/ComfyUI-WD14-Tagger"

[[custom_nodes]]
url = "https://github.com/11cafe/comfyui-workspace-manager"

[[custom_nodes]]
url = "https://github.com/jags111/efficiency-nodes-comfyui"

[[custom_nodes]]
url = "https://github.com/WASasquatch/was-node-suite-comfyui"

[[custom_nodes]]
url = "https://github.com/mcmonkeyprojects/sd-dynamic-thresholding"

[[custom_nodes]]
url = "https://github.com/rgthree/rgthree-comfy"

[[custom_nodes]]
url = "https://github.com/yolain/ComfyUI-Easy-Use"